<?php
//get vars
$page = 100;
$pageName = 'Terms of Condition';
$title = 'Web Design Scottsdale, Print, Graphics, SEO, Marketing, Phoenix Arizona';
$description = 'Markit Media is a professional Web Design, Print, Graphics, Marketing, SEO, studio in Scottsdale Arizona.';
$keywords = 'Scottsdale Web Design, Scottsdale Print, Scottsdale Graphic Design, SEO Scottsdale, Marketing Scottsdale, Php Programming Scottsdale';
$bottomDescription = "<p>Markit Media is a one stop shop for all your Web, Graphic, Print and Marketing needs. We are a full service web design company in the United States. We are located here in the valley in Scottsdale Arizona. We offer informational and E-Commerce web sites with HTML and Flash designs. Markit Media can help promote your small business online. We build professional, custom designed, websites. We have packages for new business that include logo and brand identity, 1000 business cards, 1000 tri-fold brochures, custom designed letterhead, and 5 page informative style website.</p>
                	  <p>Markit Media, Scottsdale Web Design, Scottsdale Marketing, Scottsdale Web Developer, Scottsdale Print, Scottsdale Printing, Scottsdale Graphic Design, Professional Marketing Scottsdale AZ, Professional Marketing Phoenix AZ, Professional Marketing Arizona, Professional Web design Scottsdale Arizona, Professional Web Design Phoenix Arizona, Professional Web Design Arizona, Professional Printing Scottsdale Arizona, Professional Printing Phoenix Arizona, Professional Printing Arizona, Professional Business Cards Scottsdale Arizona, Professional Business Cards Phoenix Arizona, Professional Business Cards Arizona.</p>";
require_once('header.php');
?>
<div id="content">
	<div id="contentTop"></div>
    <div id="contentBody">
    	<div class="wrapper">
        	<div class="welcome">
                <h1>Website Design Services Agreement</h1>
                <p>The following Agreement describes Terms and Conditions governing Website and/or Design work between Markit Media Group LLC and its Clients, (hereinafter designated "Markit Media" and "Client" respectively).</p>
                <ol>
                  <li><b>Estimates and Pricing</b> – A free Estimate and Consultation is provided before any other work begins and prior to any monetary transaction. The estimate will cover a Standard Web Package (see definition below) and is based on the size, scope and special requirements requested. The estimate is tunable during the development process and the final cost is to be within +/- 10% of the original estimate (any increase must be justified by Markit Media).</li>
                  <li><b>Estimate Adjustment</b> - The Estimate may be downwardly adjusted due to such things as one or more of the Requirements being marked for removal from the final design by the Client. Another reason for downward adjustment is in the event of a Requirement becoming infeasible due to software inadequacies or Web Hosting technical limitations. Estimates may be upwardly adjusted if special Requirements are added, if the Web Host selected by Client presents unforeseen problems causing delay and extra work for Markit Media. Client and Markit Media agree to make good faith attempts to hold estimates firm.</li>
                  <li><b>Payment</b> – After the Estimate / Consultation, submission of a signed and dated Design Services Contract is required before work begins. Fifty (50%) percent of the Estimate is due upfront. Send all funds to the address at the bottom of the document. Funds are accepted in cash (if exchanged in person), Debit or Credit Card, Personal Check, or bank Certified Funds. Markit Media takes no responsibility for cash sent through Mail. If personal check for payment does not clear due to insufficient funds, Development will stop until a new check is cleared. A $25 charge will be assessed for any bounced checks. All deposit monies are non- refundable.</li>
                  <li><b>Design Services Agreement</b> – The contract is to be signed and dated and sent via US mail or other client- approved carrier to the address at the bottom of the document. This will be signed and dated by Markit Media and returned promptly.</li>
                  <li><b>Ownership</b> - When all payments are received in full, then the website and all extra design items contracted for in the Requirements Document such as Logos and Brochures etc. become the property of Client. At this point, Client reserves the right to make future changes through any agent he/she designates. It is not mandatory to retain Markit Media for further modifications. Web Authoring IDs and Password information supplied for the purpose of Developing and Publishing Client's Website must be returned to Client (i.e. must not be used further without Client's written permission). It is recommended that Client change the Password for the Web Authoring ID provided to Markit Media, unless Client enters into a Maintenance Agreement with Markit Media.</li>
                  <li><b>Standard Web Package</b> – Includes Requirements & Review, Design & Review (may include a Prototype), 2 Phases of Development & Testing, Publishing of completed Website, Minor content maintenance for 30 days. Hosting and Domain(s) are also configured for Client as are any Email IDs which need to be set up on Server. Read subsequent headings for more detail on the Development Process.</li>
                  <li><b>Requirements</b> – Requirements are discussed at the Estimate and Consultation phase referenced above. These become input to the +/- 10% Estimate. Once the 50% deposit is returned and this contract is signed and dated, Requirements are set to writing, working jointly with Client. This documentation specifies the structure and parameters of the website. In addition, functionality, content headings, various special web components are also addressed. This documentation requires acceptance from Client in order to proceed to Design. Email acceptance of the Requirements is permitted to speed up the process. Requirements may still be modified during the Design Phase.</li>
                  <li><b>Web Hosting</b> - Concurrent with the Requirements phase, Client registers his/her vanity Domain Name(s) or uses an existing registered vanity Domain or Personal Web Page space provided by Client's ISP. Also, Client will secure Web Hosting Services if using a vanity Domain. Further, Client supplies a Web Authoring ID and Password for Markit Media to use for the purpose of Developing and Publishing Client's Website. Failure to do so may delay progress of the Development Process. Free assistance is available to Client by Markit Media in securing Domain and Hosting resources.</li>
                  <li><b>Design</b> – From the Requirements, we proceed into Design. More detail is addressed, including, but not limited to, font selection, themes, formatting and general content. A design prototype will be designed and delivered for approval. Changes can be made to the design until final approval has been made. Design prototype requires acceptance from Client in order to proceed to Coding/Testing. Email acceptance of Design is permitted to speed up the process. Changes to design after final approval may be subject to charge.</li>
                  <li><b>Development & Testing</b> – Once the design has been approved, the website will move to the development phase in which the design will be optimized for HTML/Flash and broken out into CSS and pages based on content provided. The website will be not be uploaded to the client's web server until full payment is cleared. The website will placed in a "test" folder until it is approved to go live and full payment is cleared.</li>
                  <li><b>Written Content</b> - Further written content for the web page is the responsibility of the Client. Unless, Client contracts for Content Writing, Client's words will be pasted verbatim into the web pages. Markit Media is not responsible for fixing grammatical, syntax, spelling, or style errors in Client's words unless they are the result of Markit Media's Content Writing or due to errors translating Client's words into the finished product. All errors must be caught and fixed within the 30 day minor content maintenance period (see below).</li>
                  <li><b>Bug Fixing</b> – It is Markit Media's responsibility to provide good faith Testing efforts to reduce the possibility of errors in the finished product. Also, it is Markit Media's responsibility to fix errors left after Development and Testing. For a period of 30 days from receipt of the final payment, Markit Media must fix all bugs reported or introduced, either by Markit Media or Client's Web Host.</li>
                  <li><b>Maintenance</b> – The only free maintenance has been specified in the Bug Fixing heading. All other modifications such as functional enhancements or content updates are not covered and will incur additional charges. This maintenance is billed on either: a) an hourly basis for small tasks b) a one-time set price for a group of enhancements, or c) a monthly fee if Client contracts for a regular volumes updates. These updates cover a "reasonable and customary" number of monthly hours agreed upon by Markit Media and Client.</li>
                  <li><b>Maintenance Process</b> – Due to its smaller scope, Maintenance is essentially a Condensed Development Process, with one (1) phase of Coding and Testing. Estimates remain as before unless Client contracted to a monthly fee due at the end of each month. Otherwise, final payment for work is due immediately after publishing of changes to Client's Domain.</li>
                  <li><b>Contract Flexibility</b> – Timing: Other than payment obligations, no strict time limits exist. Markit Media will complete all work as quickly as possible when all of Client's obligations are complete at each checkpoint of the process (e.g. Acceptance of Requirements, Written Content submitted by Client etc). Events such as business travel, vacations, or unforeseen non-business obligations on the part of Client and/or Markit Media may impede the progress of Development, but no penalty exists for either party due to such circumstances.</li>
                  <li><b>Disputes</b> – Markit Media seeks above all to talk and resolve any issues in the event of contract dispute. Client will never be required to enter a rigged and costly arbitration process in order to resolve disputes.</li>
                  <li><b>Additional Terms Applied</b> – All terms specified herein will supersede any contradictory terms above (please reference clause number if modifying any previous clause). Any new clauses will supplement areas not previously addressed by standard document. Please attach a separate page for Additional Terms.</li>
                  <li><b>Branding</b> - Markit Media reserves the right to place "Website Designed by Markit Media" on each webpage. Also, Markit Media reserves the right to use any website built by Markit Media as an example or on our portfolio. Client may opt out for an additional fee.</li>
                  <li><b>Confidential Information</b> – Markit Media hereby acknowledges that they will be given access to confidential and proprietary information of "the client" including, but not limited to, technical information, business information, and other information designated as confidential. Confidential information does not include (i) information already known or independently developed by the recipient; (ii) information in the public domain through no wrongful act of the recipient, or (iii) information received from a third party who was free to disclose it.</li>
                </ol>
                <div class="clear"></div>
            </div>
        	<div class="hr"></div>
<?php
require_once('footer.php');
?>